{% set name = "pyprobables" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyprobables-{{ version }}.tar.gz
  sha256: 9a1ddce3c59e89bf8fb918b507adb72b4f526e897f7129d75f786b38e8c254f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61.2.0
    - wheel
    - pip
  run:
    - python >=3.6

test:
  imports:
    - probables
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Probabilistic data structures in python
  description: |
    This package is a library of probablistic data
    structures written in pure python including Bloom Filters,
    Cuckoo Filters, Count-Min Sketches, and Quotient Filters
  license: MIT
  license_file: LICENSE
  home: https://github.com/barrust/pyprobables
  dev_url: https://github.com/barrust/pyprobables
  doc_url: https://pyprobables.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - barrust
